### ISSUE TITLE
Add a border around generated QR codes

### ISSUE THREAD

**Issue by sbrl** [bizzycola/qrcode-generator#1]
....otherwise many devices will have trouble scanning the generated QR Codes.

(Also, a quick reference link to https://github.com/zxing/zxing/wiki/Barcode-Contents couldn't hurt)

**Comment by bizzycola** [comment]
Added a white border around the box and added a little help icon on the left side of the contents field to that link.

**Comment by sbrl** [comment]
Awesome!

I'm not sure that the border is quite wide enough though, since [this post](https://qrworld.wordpress.com/2011/08/09/the-quiet-zone/) (and others) suggest that the border (or "quiet zone") should be at least as wide as 4 modules (the little black squares) in the code.

**Comment by bizzycola** [comment]
I increased the border width, seems like it should be good now but let me know if it is still too small. Thanks!
