### ISSUE TITLE
Feature Request: Support WiFi Sign-Up QR Codes

### ISSUE THREAD

**Issue by duggym122** [bizzycola/qrcode-generator#2]
As the title says, I would like to request support for generating wifi-signup QR codes

**Comment by tamimology** [comment]
great idea, I second that

**Comment by bizzycola** [comment]
Done and pushed to the repo.

Added a second row with a field for Wifi SSID/Password. Quite simple for now as it'll only support WPA/WPA2/WPA3, but I may expand the UI later to support more options and other kinds of QR codes that exist out there.

Here's a screenshot:
![image](https://github.com/bizzycola/qrcode-generator/assets/845115/8cdd4049-320d-4954-b197-446c44cb3d12)
